services:
    - type: web
    name: nasa-mission-control-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
            - key: PYTHON_VERSION
        value: 3.12.0
            - key: DATABASE_URL
        fromDatabase:
          name: mission_control
          property: connectionString
            - key: REDIS_URL
        fromService:
          name: mission_redis
          type: redis
          property: connectionString

databases:
    - name: mission_control
    databaseName: mission_control
    user: postgres

    - name: mission_redis
    type: redis
    plan: free