apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: postgres
    database: mission_control
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true
